name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Run positive | negative | other
        required: true
        default: positive
        type: choice
        options:
          - positive
          - negative
          - all


jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
                curl -o /tmp/chrome.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chrome-linux64.zip
                sudo unzip /tmp/chrome.zip -d ./binaries

      - name: Install Chrome WebDriver
        run: |
                curl -o /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip
                sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
                sudo chmod +x /usr/local/bin/chromedriver-linux64/chromedriver

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: positive
        if: "github.event.inputs.deployment_target == 'positive'"
        run: pytest -m positive

      - name: negative
        if: "github.event.inputs.deployment_target == 'negative'"
        run: pytest -m negative

      - name: Run tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest -m "not positive and not negative"
