name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
                curl -o /tmp/chrome.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chrome-linux64.zip
                sudo unzip /tmp/chrome.zip -d ./binaries
        

      - name: List contents of 'binaries' directory
        run: |
                ls -la binaries

      - name: List contents of 'binaries' directory
        run: |
                ls -la binaries/chrome-linux64
              

      - name: Install Chrome WebDriver
        run: |
                curl -o /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip
                sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
                echo "Current directory: $(pwd)"
                echo "Contents of current directory:"
                ls -la
          
                sudo chmod +x /usr/local/bin/chromedriver-linux64/chromedriver

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest



